### ISSUE TITLE
Compatibility with new OD URLs

### ISSUE THREAD

**Issue by samsucik** [xslidian/omnibox-oxford-dictionaries#1]
OD changed their website and the URLs changed as well, for example to search in the English dictionary, the base URL is en.oxforddictionaries.com and definitions are found at en.oxforddictionaries.com/definition/word. At the moment the extension doesn't work, the URLs need to be updated in the code, for example a search request can be sent to "en.oxforddictionaries.com/search?query=WORD&filter=dictionary".

**Comment by xslidian** [comment]
Thank you very much for your report. Sorry that I haven't noticed the change yet.

I just unpublished the extension from the Chrome web store.
I'll publish it again as soon as enough tests were done.

**Comment by xslidian** [comment]
Hello,

I've uploaded v0.7 to the Chrome webstore, which should work with the new ODs.

**Comment by samsucik** [comment]
Hey, thank you so much for updating the extension! It's my favourite as I'm
a non-native speaker :-)

Just a minor bug: when using the living dictionaries and choosing from the
list of suggestions, it puts '/definition/' before the actual string, see
the picture attached. It's fine but fixing it would certainly make the
extension attractive for more people.

*Samuel Sučík*

**Comment by samsucik** [comment]
Hey, thank you so much for updating the extension! It's my favourite as I'm
a non-native speaker :-)

Just a minor bug: when using the living dictionaries and choosing from the
list of suggestions, it puts '/definition/' before the actual string, see
the picture attached. It's fine but fixing it would certainly make the
extension attractive for more people.
![od-bug](https://cloud.githubusercontent.com/assets/7470182/21109412/df833a9c-c090-11e6-83a5-f3beeecae9d2.png)
